- name: Postgres
  hosts: all
  become: yes
  tasks:
  #Устанавливаем vim и telnet (для более удобной работы с хостами)
  - name: install base tools
    apt:
      name:
        - vim
        - telnet
        - acl
      state: present
      update_cache: true

#Запуск ролей install_postgres и postgres_replication на хостах node1 и node2
- name: install postgres 15
  hosts: node1,node2
  become: yes
  roles:  
    - install_postgres
  tags:
    - install_postgres

#Запуск ролей install_postgres и postgres_replication на хостах node1 и node2
- name: set up replication
  hosts: node1,node2
  become: yes
  roles:  
    - postgres_replication
  tags:
    - postgres_replication


#Запуск роли install_barman на всех хостах
- name: set up backup
  hosts: all
  become: yes
  roles:
    - install_barman
  tags:
    - install_barman
